### ISSUE TITLE
OpenAL Soft CMake file includes Windows 10 SDK version in path

### ISSUE THREAD

**Issue by dpogue** [H-uru/PlasmaPrefix#7]
Not sure what we can do about this since it's probably an upstream problem, but it keeps tripping people up and I want to track it somewhere.

When the devlibs.zip bundle is built, the OpenAL.cmake config file includes an instruction to load the WinMM.lib system library from the Windows SDK. It points specifically to the SDK path that was used on the system that compiled the devlibs, and this path includes the SDK version number.

When installing Visual Studio and the Windows SDK, it's common to just pick the latest SDK version.

This leads to people running into compiler errors about not being able to open
`C:\Program Files(x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\WinMM.Lib`

### Workaround
In the extracted devlibs bundle, edit `share/openal-soft/OpenALConfig.cmake` line 57 and change the SDK version in the path to match the version installed on your development machine.

**Comment by Hoikas** [comment]
I think this was fixed in an [upstream vcpkg changeset](https://github.com/microsoft/vcpkg/commit/006a133d39a72cc7ec60f651e224ca8a3b41c734#diff-083b054a99ecded0d43d2f6aff7f0629R60) and will be corrected on our end with an update to the devlibs bundle.

**Comment by Hoikas** [comment]
Sadly, it appears I was mistaken and the borked WinMM include is still present in the latest release.

**Comment by Hoikas** [comment]
While this is ultimately a problem in openal-soft itself not creating relocatable packages, the immediate problem here will be fixed by microsoft/vcpkg#15634.

**Comment by Hoikas** [comment]
Release 2021.01.18 incorporates the fix for this.
